<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class UserInfo {

  static $swaggerTypes = array(
      'signin_count' => 'int',
      'signedupOn' => 'string',
      'nickname' => 'string',
      'pkey' => 'string',
      'lastname' => 'string',
      'alerts_eanbled' => 'bool',
      'firstname' => 'string',
      'news_eanbled' => 'bool',
      'support_eanbled' => 'bool',
      'photo' => 'array[int]',
      'support_email' => 'string',
      'guid' => 'string',
      'id' => 'float',
      'pswd_salt' => 'string',
      'token' => 'string',
      'primary_email' => 'string',
      'roles' => 'array[RoleInfo]',
      'active' => 'bool',
      'signedinOn' => 'string',
      'trial' => 'bool',
      'claimed_id' => 'string',
      'storage' => 'int'

    );

  public $signin_count; // int
  public $signedupOn; // string
  public $nickname; // string
  public $pkey; // string
  public $lastname; // string
  public $alerts_eanbled; // bool
  public $firstname; // string
  public $news_eanbled; // bool
  public $support_eanbled; // bool
  public $photo; // array[int]
  public $support_email; // string
  public $guid; // string
  public $id; // float
  public $pswd_salt; // string
  public $token; // string
  public $primary_email; // string
  public $roles; // array[RoleInfo]
  public $active; // bool
  public $signedinOn; // string
  public $trial; // bool
  public $claimed_id; // string
  public $storage; // int
  }

